export enum Escolaridade {
    ENSINO_FUNDAMENTAL_INCOMPLETO = 'ENSINO_FUNDAMENTAL_INCOMPLETO',
    ENSINO_FUNDAMENTAL_COMPLETO = 'ENSINO_FUNDAMENTAL_COMPLETO',
    ENSINO_MEDIO_INCOMPLETO = 'ENSINO_MEDIO_INCOMPLETO',
    ENSINO_MEDIO_COMPLETO = 'ENSINO_MEDIO_COMPLETO',
    ENSINO_TECNICO = 'ENSINO_TECNICO',
    GRADUACAO_INCOMPLETA = 'GRADUACAO_INCOMPLETA',
    GRADUACAO_CURSANDO = 'GRADUACAO_CURSANDO',
    GRADUACAO_COMPLETA = 'GRADUACAO_COMPLETA',
    POS_GRADUACAO = 'POS_GRADUACAO',
    MESTRADO = 'MESTRADO',
    DOUTORADO = 'DOUTORADO',
    POS_DOUTORADO = 'POS_DOUTORADO',
}
